import type { Restaurant, Category, MenuItem } from "@/lib/database.types";

export const DEMO_RESTAURANT: Restaurant = {
  id: "demo-restaurant-1",
  owner_id: "demo-user-1",
  name: "Hotel Panchratna Executive",
  slug: "hotel-panchratna",
  tagline: "Authentic Solapuri Flavours & Royal Dining",
  description:
    "Serving Solapur authentic Maharashtrian delicacies, spicy mutton sukka, jawar bhakri, and exquisite North Indian & Tandoor dishes since 1998.",
  phone: "+91 98220 12345",
  email: "contact@panchratnasolapur.com",
  whatsapp: "+919822012345",
  address: "Opposite Old Pune Naka, Near Saat Rasta",
  city: "Solapur",
  state: "Maharashtra",
  country: "India",
  postal_code: "413003",
  currency: "INR",
  logo_url: null,
  cover_url: null,
  cover_image_url: null,
  banner_url: null,
  theme_color: "#ea580c",
  secondary_color: "#0f172a",
  template: "classic",
  font_family: "Inter",
  opening_hours: "11:00 AM - 11:30 PM (Daily)",
  is_active: true,
  status: "active",
  subscription_plan: "pro",
  subscription_status: "active",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    restaurant_id: "demo-restaurant-1",
    name: "Solapuri Specialties",
    description: "Famous local dishes made with authentic groundnut chutney & spices",
    icon: "Flame",
    image_url: null,
    sort_order: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    restaurant_id: "demo-restaurant-1",
    name: "Tandoori Starters",
    description: "Charcoal smoked skewers and hot appetizers",
    icon: "Utensils",
    image_url: null,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    restaurant_id: "demo-restaurant-1",
    name: "Main Course (Veg & Non-Veg)",
    description: "Rich paneer curries, mutton rassa, and special preparations",
    icon: "Soup",
    image_url: null,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    restaurant_id: "demo-restaurant-1",
    name: "Breads & Bhakri",
    description: "Hot tandoor naans and authentic Solapuri Jowar Bhakri",
    icon: "Pizza",
    image_url: null,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    restaurant_id: "demo-restaurant-1",
    name: "Desserts & Beverages",
    description: "Chilled masala chaas, gulab jamun with rabdi",
    icon: "Coffee",
    image_url: null,
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_ITEMS: MenuItem[] = [
  {
    id: "item-1",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-1",
    name: "Solapuri Shenga Chutney & Kadak Bhakri Thali",
    description:
      "Crunchy roasted groundnut garlic chutney served with hot Jowar bhakri, thecha, raw onion, and fresh butter.",
    price: 180,
    offer_price: 200,
    food_type: "veg",
    spice_level: "spicy",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "10-15 mins",
    calories: null,
    allergens: ["Peanuts"],
    sort_order: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-2",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-1",
    name: "Solapuri Mutton Sukka",
    description:
      "Slow-cooked tender goat meat tossed in spicy black masala roasted dry coconut paste.",
    price: 380,
    offer_price: null,
    food_type: "non-veg",
    spice_level: "extra_spicy",
    badge: "chef_special",
    image_url: null,
    is_available: true,
    preparation_time: "20-25 mins",
    calories: null,
    allergens: [],
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-3",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-2",
    name: "Paneer Tikka Angara",
    description:
      "Fresh cottage cheese cubes marinated in Kashmiri chili yogurt and roasted over hot charcoal.",
    price: 260,
    offer_price: 290,
    food_type: "veg",
    spice_level: "medium",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "15 mins",
    calories: null,
    allergens: ["Dairy"],
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-4",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-3",
    name: "Paneer Butter Masala",
    description:
      "Soft cottage cheese simmered in a silky tomato gravy with rich butter and fenugreek leaves.",
    price: 270,
    offer_price: 300,
    food_type: "veg",
    spice_level: "medium",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "15-20 mins",
    calories: null,
    allergens: ["Dairy"],
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-5",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-3",
    name: "Butter Chicken Delhi Style",
    description:
      "Tandoor roasted chicken simmered in a velvety tomato makhani gravy enriched with fresh cream.",
    price: 340,
    offer_price: 370,
    food_type: "non-veg",
    spice_level: "mild",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "20 mins",
    calories: null,
    allergens: ["Dairy"],
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-6",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-4",
    name: "Jowar Bhakri (2 Pcs)",
    description:
      "Freshly patted warm sorghum bread, a traditional staple of Solapur.",
    price: 40,
    offer_price: null,
    food_type: "veg",
    spice_level: "mild",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "5-10 mins",
    calories: null,
    allergens: [],
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-7",
    restaurant_id: "demo-restaurant-1",
    category_id: "cat-5",
    name: "Solapuri Masala Chaas (Chilled)",
    description:
      "Refreshing spiced buttermilk tempered with roasted cumin, mint, and rock salt.",
    price: 50,
    offer_price: null,
    food_type: "veg",
    spice_level: "mild",
    badge: "bestseller",
    image_url: null,
    is_available: true,
    preparation_time: "2 mins",
    calories: null,
    allergens: ["Dairy"],
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
